/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2026-02-09 01:18:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.lang.*;

public final class total_002dpercentage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Student Percentage Calculator</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h2>Student Percentage Calculator</h2>\r\n");
      out.write("\r\n");
      out.write("<!-- Input Form -->\r\n");
      out.write("<form method=\"post\">\r\n");
      out.write("    \r\n");
      out.write("    Student Name:\r\n");
      out.write("    <input type=\"text\" name=\"name\" required>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("    Roll Number:\r\n");
      out.write("    <input type=\"text\" name=\"roll\" required>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("    Marks in Subject 1:\r\n");
      out.write("    <input type=\"number\" name=\"marks1\"  required>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("    Marks in Subject 2:\r\n");
      out.write("    <input type=\"number\" name=\"marks2\"  required>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("    Marks in Subject 3:\r\n");
      out.write("    <input type=\"number\" name=\"marks3\"  required>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("    Marks in Subject 4:\r\n");
      out.write("    <input type=\"number\" name=\"marks4\"  required>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("    Marks in Subject 5:\r\n");
      out.write("    <input type=\"number\" name=\"marks5\" required>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("    <input type=\"submit\" value=\"Calculate Percentage\">\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");

    // Run calculation ONLY after form submit
    if(request.getMethod().equalsIgnoreCase("POST")) {

        try {
            String name = request.getParameter("name");
            String roll = request.getParameter("roll");

            double marks1 = Double.parseDouble(request.getParameter("marks1"));
            double marks2 = Double.parseDouble(request.getParameter("marks2"));
            double marks3 = Double.parseDouble(request.getParameter("marks3"));
            double marks4 = Double.parseDouble(request.getParameter("marks4"));
            double marks5 = Double.parseDouble(request.getParameter("marks5"));

            double totalMarks = marks1 + marks2 + marks3 + marks4 + marks5;
            double percentage = (totalMarks / 500) * 100;

            String division;

            if (percentage >= 80)
                division = "First Division";
            else if (percentage >= 60)
                division = "Second Division";
            else if (percentage >= 40)
                division = "Third Division";
            else
                division = "Fail";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>Result</h3>\r\n");
      out.write("Name: <b>");
      out.print( name );
      out.write("</b> <br>\r\n");
      out.write("Roll Number: <b>");
      out.print( roll );
      out.write("</b> <br>\r\n");
      out.write("Total Marks: <b>");
      out.print( totalMarks );
      out.write("/500</b> <br>\r\n");
      out.write("Percentage: <b>");
      out.print( String.format("%.2f", percentage) );
      out.write("%</b> <br>\r\n");
      out.write("Division: <b>");
      out.print( division );
      out.write("</b>\r\n");
      out.write("\r\n");

        } catch(Exception e) {

      out.write("\r\n");
      out.write("    <p style=\"color:red;\">Invalid input! Please enter valid numbers for marks.</p>\r\n");

        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
